### ISSUE TITLE
Will this work with windows as is?

### ISSUE THREAD

**Issue by reo4ua** [nebhead/PlexPostProc#12]
If I follow the instructions as written, will this script execute on a windows 10 machine?

**Comment by nebhead** [comment]
Apologies, but this script is written for bash or variants of a linux shell.  You would need to re-write this for Windows 10.

**Comment by nebhead** [comment]
Closing.

**Comment by reo4ua** [comment]
ok thanks for taking the time to reply.
Thanks,

Raymond
