### ISSUE TITLE
writes out as mkv instead of mp4 

### ISSUE THREAD

**Issue by tommycahir** [nebhead/PlexPostProc#13]
Hi
I noticed that the script was actually writing the new file out as mkv rather than mp4 so checking the script I see that the below line:

mv -f "$TEMPFILENAME" "${FILENAME%.ts}.mkv" # Move completed temp to original filename

should be 
mv -f "$TEMPFILENAME" "${FILENAME%.ts}.mp4" # Move completed temp to original filename

**Comment by nebhead** [comment]
Sorry for ignoring this one for so long.  I've updated the script today.  I'm going to be merging branches so both FFMpeg and HandBrake are generating MKV.
