### ISSUE TITLE
(QUESTION) 

### ISSUE THREAD

**Issue by maxcore** [nebhead/PlexPostProc#14]
Hi ,

i use plex on unraid with a docker and i need to reinstall handbrake in the plex docker each time  the plex as a new version has install.

My question 1 : how i can fix this ? 
My question 2: I can use the handbraker docker in unraid ?

your script is magic but i need to install handbrake in the plex docker with the terminal ..
thx

**Comment by nebhead** [comment]
Glad you're enjoying the script.  I am also running this inside of a docker, but just on a Linux server.  I totally get the frustration of having to re-install Handbrake each time you upgrade - it's a pain for sure.  I have to do the same, but usually only if I do a pull and/or create a new container.  I'm guessing that Unraid does that when you do a new version update.  

To address your questions, I'm not sure we can get around this, other than to create your own Docker container which you manage the contents - probably not ideal in your case.  I'm not a Docker expert, but it might be possible for us to setup a volume for transcodes that another Docker is watching, like your Handbraker docker.  If you'd like to do a little digging on this one and do a pull-request (if you figure it out) that would be awesome.
