### ISSUE TITLE
Feature Request - Not Issue

### ISSUE THREAD

**Issue by shdwkeeper** [nebhead/PlexPostProc#16]
You think about possibly adding Comskip to this script, so it removes the commercials first than transcodes the file? That would be great.  I'm still testing this out at the moment.

Thanks, keep up good work.

**Comment by nebhead** [comment]
Yeah, I had messed around with adding comskip, but frankly, I couldn't get it to work any better than the comskip that is native in the Plex server - so I decided I'd just use the Plex comskip where needed.   

Thanks for the praise though!
