### ISSUE TITLE
Getting Error 127 when using this file.

### ISSUE THREAD

**Issue by Hollier** [nebhead/PlexPostProc#20]
Hi, 

I am using Debian 10 / Not using Docker so directory install Plex Media Server version Version 1.20.1.3252

I am getting this error when I try and use this file. 
20210802-220206: Starting transcode of /media/nas/TV/TV/.grab/7b923c65a4363383d3a2d730606ff161462de4d6-4488fda215b35da7d4567b111aaa1b37ed1039b1/T$
You have selected HandBrake
ERROR # 127 : Failed to convert using Handbrake.

What am I doing wrong here? 

Thank you

**Comment by nebhead** [comment]
Can you send the full log?  Do you have handbrake installed and in the path?

**Comment by Hollier** [comment]
Yes, Handbrake installed and in the path, not docker. 

Plex log 

:

06.185 [0x7f6245ffb700] VERBOSE - [IDLE] * http_download - /library/parts/79458/1627852440/file.mkv?X-Plex-Token=xxxxxxxxxxxxxxxxxxxx&X-Plex-Product=Plex%20for%20Samsung&X-Plex-Platform=Tizen&X-Plex-Platform-Version=5&X-Plex-Model=UN65RU9000FXZC&X-Plex-Device=19_MUSEM_UHD&X-Plex-Device-Name=TV%202019&X-Plex-Device-Vendor=Samsung&X-Plex-Device-Screen-Resolution=1920x1080&X-Plex-Drm=playready%3Avideo&X-Plex-Version=5.20.1&X-Plex-Client-Identifier=ql6tp21kqom2gkx21vwa5yww&X-Plex-Language=en&X-Plex-Features=external-media%2Cindirect-media&Accept=application%2Fjson&Accept-Language=en - 1 active item(s)
Aug 02, 2021 22:02:06.185 [0x7f6245ffb700] VERBOSE - [IDLE] * http_download - /player/proxy/poll?deviceClass=pc&protocolVersion=3&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&timeout=1&X-Plex-Product=Plex%20for%20Windows&X-Plex-Version=1.33.0.2444-a220eae4&X-Plex-Client-Identifier=twxul04ep6dqr67sy9crj8uy&X-Plex-Platform=windows&X-Plex-Platform-Version=10.0.19043&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2Cindirect-media&X-Plex-Model=standalone&X-Plex-Device-Name=LAPTOP-MG7DV13R&X-Plex-Device-Screen-Resolution=1280x705%2C1600x900&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=xxxxxxxxxxxxxxxxxxxx&X-Plex-Language=en - 1 active item(s)
Aug 02, 2021 22:02:06.185 [0x7f6245ffb700] VERBOSE - [IDLE] * http_download - /player/proxy/poll?deviceClass=pc&protocolVersion=3&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&timeout=1&X-Plex-Product=Plex%20for%20Windows&X-Plex-Version=1.33.0.2444-a220eae4&X-Plex-Client-Identifier=twxul04ep6dqr67sy9crj8uy&X-Plex-Platform=windows&X-Plex-Platform-Version=10.0.19043&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2Cindirect-media&X-Plex-Model=standalone&X-Plex-Device-Name=LAPTOP-MG7DV13R&X-Plex-Device-Screen-Resolution=1406x705%2C1920x1080&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=xxxxxxxxxxxxxxxxxxxx&X-Plex-Language=en - 1 active item(s)
Aug 02, 2021 22:02:06.185 [0x7f6245ffb700] VERBOSE - [IDLE] * http_download - /player/proxy/poll?deviceClass=pc&protocolVersion=3&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cplayqueues&timeout=1&X-Plex-Product=Plex+for+Samsung&X-Plex-Platform=Tizen&X-Plex-Platform-Version=5&X-Plex-Model=UN65RU9000FXZC&X-Plex-Device=19_MUSEM_UHD&X-Plex-Device-Name=TV+2019&X-Plex-Device-Vendor=Samsung&X-Plex-Device-Screen-Resolution=1920x1080&X-Plex-Drm=playready:video&X-Plex-Version=5.20.1&X-Plex-Client-Identifier=ql6tp21kqom2gkx21vwa5yww&X-Plex-Language=en&X-Plex-Features=external-media,indirect-media&X-Plex-Token=xxxxxxxxxxxxxxxxxxxx - 1 active item(s)
Aug 02, 2021 22:02:06.185 [0x7f6245ffb700] VERBOSE - [IDLE] * transcoder - b83cb8e9-e46a-4b6f-aea9-243f984444bf - 1 active item(s)
Aug 02, 2021 22:02:06.185 [0x7f6245ffb700] VERBOSE - [IDLE] * transcoder - c2b72581-50f0-4125-8749-06d506d7b984 - 1 active item(s)
Aug 02, 2021 22:02:06.185 [0x7f6245ffb700] DEBUG - Content-Length is -1 (of total: -1).
Aug 02, 2021 22:02:06.350 [0x7f61cbfff700] DEBUG - Removing intermediate files at path The Bachelorette (2003) - S17E09 - The Bachelorette.ts
Aug 02, 2021 22:02:06.350 [0x7f61cbfff700] DEBUG - Job running: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Scripts/PlexPostProc.sh' '/media/nas/TV/TV/.grab/7b923c65a4363383d3a2d730606ff161462de4d6-4488fda215b35da7d4567b111aaa1b37ed1039b1/The Bachelorette (2003) - S17E09 - The Bachelorette.ts'
Aug 02, 2021 22:02:06.350 [0x7f61cbfff700] DEBUG - Jobs: Starting child process with pid 11764
Aug 02, 2021 22:02:06.363 [0x7f625ce14700] VERBOSE - JobManager: child process with handle 11764 exited
Aug 02, 2021 22:02:06.363 [0x7f625ce14700] DEBUG - Jobs: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Scripts/PlexPostProc.sh' exit code for process 11764 is 127 (failure)
Aug 02, 2021 22:02:06.363 [0x7f61cbfff700] ERROR - Recorder: Postprocessing script '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Scripts/PlexPostProc.sh' exited with error code 127.
Aug 02, 2021 22:02:06.363 [0x7f61cbfff700] DEBUG - Grabber: Scheduling 'The Bachelorette - E9 - The Bachelorette' for assimilation.
Aug 02, 2021 22:02:06.365 [0x7f61d1ffb700] DEBUG - Subscription: Failed to resolve subscription for episode 'grandparentGuid: plex://show/5fc6ac16139621002d3f079a grandparentThumb: https://metadata-static.plex.tv/2/gracenote/27b2285ac3ea611d1f69be5bd65164de.jpg grandparentTitle: The Bachelorette grandparentYear: 2003 guid: plex://episode/60ecf610be9247002cc91de7 index: 9 originallyAvailableAt: 2021-08-02 parentGuid: plex://season/5fc6ac16139621002d3f079a/17 parentIndex: 17 parentTitle: Season 17 ratingKey: plex%3A%2F%2Fepisode%2F60ecf610be9247002cc91de7 thumb: https://metadata-static.plex.tv/8/gracenote/8c9dc6b13d148c79c3ffadf1667b6487.jpg title: The Bachelorette type: 4 year: 2021' to library item
Aug 02, 2021 22:02:06.365 [0x7f61d1ffb700] DEBUG - Assimilator: Postprocessing, we're going to put `The Bachelorette - E9 - The Bachelorette` in `/media/nas/TV/TV/The Bachelorette (2003)/Season 17/The Bachelorette (2003) - S17E09 - The Bachelorette.ts`
Aug 02, 2021 22:02:06.366 [0x7f61d1ffb700] DEBUG - Assimilator: Moving "/media/nas/TV/TV/.grab/7b923c65a4363383d3a2d730606ff161462de4d6-4488fda215b35da7d4567b111aaa1b37ed1039b1/The Bachelorette (2003) - S17E09 - The Bachelorette.log" to "/media/nas/TV/TV/The Bachelorette (2003)/Season 17/The Bachelorette (2003) - S17E09 - The Bachelorette.log"
Aug 02, 2021 22:02:06.366 [0x7f61d1ffb700] DEBUG - Assimilator: Moving "/media/nas/TV/TV/.grab/7b923c65a4363383d3a2d730606ff161462de4d6-4488fda215b35da7d4567b111aaa1b37ed1039b1/The Bachelorette (2003) - S17E09 - The Bachelorette.ts" to "/media/nas/TV/TV/The Bachelorette (2003)/Season 17/The Bachelorette (2003) - S17E09 - The Bachelorette.ts"
Aug 02, 2021 22:02:06.367 [0x7f61d2ffd700] INFO - Library section 2 (TV Shows) will be updated because of a change in '"/media/nas/TV/TV"/The Bachelorette (2003)'
Aug 02, 2021 22:02:06.367 [0x7f61d2ffd700] DEBUG - [Notify] New directory: "/media/nas/TV/TV/The Bachelorette (2003)", adding recursively.
Aug 02, 2021 22:02:06.367 [0x7f61d2ffd700] DEBUG - [Notify] Now watching "/media/nas/TV/TV/The Bachelorette (2003)"
Aug 02, 2021 22:02:06.367 [0x7f61d2ffd700] DEBUG - [Notify] Now watching "/media/nas/TV/TV/The Bachelorette (2003)/Season 17"
Aug 02, 2021 22:02:06.368 [0x7f61d1ffb700] DEBUG - Subscription: Failed to resolve subscription for episode 'grandparentGuid: plex://show/5fc6ac16139621002d3f079a grandparentThumb: https://metadata-static.plex.tv/2/gracenote/27b2285ac3ea611d1f69be5bd65164de.jpg grandparentTitle: The Bachelorette grandparentYear: 2003 guid: plex://episode/60ecf610be9247002cc91de7 index: 9 originallyAvailableAt: 2021-08-02 parentGuid: plex://season/5fc6ac16139621002d3f079a/17 parentIndex: 17 parentTitle: Season 17 ratingKey: plex%3A%2F%2Fepisode%2F60ecf610be9247002cc91de7 thumb: https://metadata-static.plex.tv/8/gracenote/8c9dc6b13d148c79c3ffadf1667b6487.jpg title: The Bachelorette type: 4 year: 2021' to library item
Aug 02, 2021 22:02:06.372 [0x7f61d1ff

**Comment by nebhead** [comment]
There should be a log for this script here: LOGFILE="$TMPFOLDER/plexpp$(date +"%Y%m%d-%H%M%S").log
Usually that is /tmp/.   Can you check that and post it?

**Comment by Hollier** [comment]
The Full log file is in the original post.

**Comment by nebhead** [comment]
Ok.  Can you try to manually run handbrake and see if it works?  Try to
replicate what the script is doing.

**Comment by Hollier** [comment]
using the same setting you are using in your script I get this. output from Handbreak. 

```
bmserver@NAS-Plex:/media/nas/Datastore/backup$ HandBrakeCLI -i Greys.Anatomy.S17E16.1080p.WEB.H264-STRONTiUM.mkv -f mkv --aencoder copy -e qsv_h264 --x264-preset veryfast --x264-profile auto -q 16 --maxHeight $RES --decomb bob -o Test
[10:49:12] Compile-time hardening features are enabled
[10:49:12] hb_init: starting libhb thread
[10:49:12] thread 7f0d8cdae700 started ("libhb")
HandBrake 20210731215317-abbc04908-master (2021080201) - Linux x86_64 - https://handbrake.fr
4 CPUs detected
Opening Greys.Anatomy.S17E16.1080p.WEB.H264-STRONTiUM.mkv...
[10:49:12] CPU:
[10:49:12]  - logical processor count: 4
[10:49:12] hb_scan: path=Greys.Anatomy.S17E16.1080p.WEB.H264-STRONTiUM.mkv, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
disc.c:333: failed opening UDF image Greys.Anatomy.S17E16.1080p.WEB.H264-STRONTiUM.mkv
disc.c:437: error opening file BDMV/index.bdmv
disc.c:437: error opening file BDMV/BACKUP/index.bdmv
bluray.c:2646: nav_get_title_list(Greys.Anatomy.S17E16.1080p.WEB.H264-STRONTiUM.mkv/) failed
[10:49:12] bd: not a bd - trying as a stream/file instead
libdvdread: Encrypted DVD support unavailable.
libdvdread: DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: vm: failed to read VIDEO_TS.IFO
[10:49:12] dvd: not a dvd - trying as a stream/file instead
Input #0, matroska,webm, from 'Greys.Anatomy.S17E16.1080p.WEB.H264-STRONTiUM.mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-05-28T04:28:30.000000Z
  Duration: 00:42:25.44, start: 0.000000, bitrate: 9281 kb/s
  Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 8639048
      DURATION        : 00:42:25.418000000
      NUMBER_OF_FRAMES: 61029
      NUMBER_OF_BYTES : 2748748800
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-28 04:28:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)
    Metadata:
      BPS             : 640000
      DURATION        : 00:42:25.440000000
      NUMBER_OF_FRAMES: 79545
      NUMBER_OF_BYTES : 203635200
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-28 04:28:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English
      BPS             : 97
      DURATION        : 00:42:10.659000000
      NUMBER_OF_FRAMES: 1004
      NUMBER_OF_BYTES : 30755
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-28 04:28:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[10:49:12] scan: decoding previews for title 1
[10:49:12] scan: audio 0x1: eac3, rate=48000Hz, bitrate=640000 English (E-AC3) (5.1 ch) (640 kbps)
Scanning title 1 of 1, preview 10, 100.00 %[10:49:13] scan: 10 previews, 1920x1080, 23.976 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1, color profile: 1-1-1
[10:49:13] libhb: scan thread found 1 valid title(s)
+ Using preset: CLI Default
+ title 1:
  + stream: Greys.Anatomy.S17E16.1080p.WEB.H264-STRONTiUM.mkv
  + duration: 00:42:25
  + size: 1920x1080, pixel aspect: 1/1, display aspect: 1.78, 23.976 fps
  + autocrop: 0/0/0/0
  + chapters:
    + 1: duration 00:42:25
  + audio tracks:
    + 1, English (E-AC3) (5.1 ch) (640 kbps) (iso639-2: eng)
  + subtitle tracks:
    + 1, English [UTF-8]
[10:49:13] Starting work at: Tue Aug  3 10:49:13 2021

[10:49:13] 1 job(s) to process
[10:49:13] json job:
{
    "Audio": {
        "AudioList": [
            {
                "Bitrate": 0,
                "DRC": 0.0,
                "Encoder": "copy:eac3",
                "Mixdown": "none",
                "PresetEncoder": "copy",
                "Quality": -3.0,
                "Samplerate": 0,
                "Track": 0
            }
        ],
        "CopyMask": [
            "copy:aac",
            "copy:ac3",
            "copy:eac3",
            "copy:dtshd",
            "copy:dts",
            "copy:mp3",
            "copy:truehd",
            "copy:flac"
        ],
        "FallbackEncoder": "av_aac"
    },
    "Destination": {
        "AlignAVStart": false,
        "ChapterList": [
            {
                "Duration": {
                    "Hours": 0,
                    "Minutes": 42,
                    "Seconds": 25,
                    "Ticks": 229089600
                },
                "Name": ""
            }
        ],
        "ChapterMarkers": false,
        "File": "Test",
        "InlineParameterSets": false,
        "Mp4Options": {
            "IpodAtom": false,
            "Mp4Optimize": false
        },
        "Mux": "mkv"
    },
    "Filters": {
        "FilterList": [
            {
                "ID": 6,
                "Settings": {
                    "mode": 0
                }
            },
            {
                "ID": 13,
                "Settings": {
                    "crop-bottom": 0,
                    "crop-left": 0,
                    "crop-right": 0,
                    "crop-top": 0,
                    "height": 1080,
                    "width": 1920
                }
            }
        ]
    },
    "Metadata": {},
    "PAR": {
        "Den": 1,
        "Num": 1
    },
    "SequenceID": 0,
    "Source": {
        "Angle": 0,
        "Path": "Greys.Anatomy.S17E16.1080p.WEB.H264-STRONTiUM.mkv",
        "Range": {
            "End": 1,
            "Start": 1,
            "Type": "chapter"
        },
        "Title": 1
    },
    "Subtitle": {
        "Search": {
            "Burn": true,
            "Default": false,
            "Enable": false,
            "Forced": false
        },
        "SubtitleList": []
    },
    "Video": {
        "ColorFormat": 0,
        "ColorMatrix": 1,
        "ColorPrimaries": 1,
        "ColorRange": 1,
        "ColorTransfer": 1,
        "Encoder": "qsv_h264",
        "Preset": "veryfast",
        "Profile": "auto",
        "QSV": {
            "AdapterIndex": 0,
            "AsyncDepth": 0,
            "Decode": false
        },
        "Quality": 16.0,
        "Turbo": false,
        "TwoPass": false
    }
}
[10:49:13] Starting Task: Encoding Pass
[10:49:13] Skipping vfr filter
[10:49:13] Skipping crop/scale filter
[10:49:13] Finished work at: Tue Aug  3 10:49:13 2021

[10:49:13] libhb: work result = 3

Encode failed (error 3).

HandBrake has exited.

```

**Comment by Hollier** [comment]
ok so it might have been my Handbreak install. I have updated it and now using your Handbreak line in the command line it now works. going to try the script in Plex.

**Comment by nebhead** [comment]
Great! Let me know.

**Comment by Hollier** [comment]
Ok it was my install of Handbreak.  It's working now. 

Thank you for your help. and thanks for the script.

**Comment by nebhead** [comment]
Great news!  Thanks and enjoy!
