### ISSUE TITLE
Hardware encoding

### ISSUE THREAD

**Issue by famewolf** [nebhead/PlexPostProc#21]
Does your post processing script allow for usage of intel quicksync?

**Comment by nebhead** [comment]
Technically speaking, the script just launches FFMPEG, or Handbrake.  So if you have either of those configured to use Intel Quick Sync hardware encoding, then it will work just fine.  If not, then it will probably just use CPU/SW encoding.  

Someone previously added the 'nvtrans' option to the script, which will attempt to use the internal Plex transcoder.  This might use the Intel Quick Sync hardware encoding, if it's selected in your settings.  However, I haven't haven't messed around with this and am not too sure if it works well.
