### ISSUE TITLE
support 480?

### ISSUE THREAD

**Issue by imzenreally** [nebhead/PlexPostProc#22]
i don't care about resolution for my dvr recordings - i just want them crushed down as much as possible - if i set res to 480 will that break the script?

**Comment by nebhead** [comment]
Should be completely fine, of course I would recommend testing it to be sure.  Give it a shot and let me know if it works for you.

**Comment by imzenreally** [comment]
will do - i'll make the change this evening - if it does i'll update and recommit

**Comment by imzenreally** [comment]
tried pushing the changes back to your repo but i haven't set up a access token and don't want to go through the effort and i dn't want to check it out on my work account :) so yes - 480 works fine - about halves the size of a file from 720

**Comment by imzenreally** [comment]
RES="720"         # Resolution to convert to:
                  # "480" = 480 Vertical Resolution
                  # "720" = 720 Vertical Resolution
                  # "1080" = 1080 Vertical Resolution

**Comment by nebhead** [comment]
Awesome, thank you!  I'll make the change directly.  Much appreciated.
