### ISSUE TITLE
QUESTION: Subtitle Passthru?

### ISSUE THREAD

**Issue by DaleyKD** [nebhead/PlexPostProc#27]
I don't know much about Handbrake, but I am trying to tweak your .sh to work for Windows using a VERY simple .bat.

Looking at the Handbrake parameters, will it pass thru the subtitles (aka - Closed Captioning) that PlexDVR/HDHomeRun put into the .ts?

**Comment by Frono** [comment]
Sorry, but I'm not a big GitHub kinda guy... But here is the change I made to do subtitles and 265 encoding
I changed the FFMpeg command line as follows below:

     ffmpeg -probesize 50M -analyzeduration 100M -i "$FILENAME" -map 0 -c:v libx265 -crf 26 -c:a copy -c:s copy "$TEMPFILENAME"

the -cs copy  makes it copy the subtitles from the input to the output.

**Comment by nebhead** [comment]
Yeah, sorry, but this is one that you may have to take up with the Handbrake team.  I'm going to close this one here, but I hope you can find a solution over there.
