### ISSUE TITLE
Failed to Move

### ISSUE THREAD

**Issue by tykisson** [nebhead/PlexPostProc#28]
Just updated to the new sript and at first I was getting error 1, then it would run constantly, now i'm getting a failed to move error. 

"Finished transcode,ERROR # 1 : Failed to move converted file: /tmp/tmp.zzWHyMdI08.mkv"

Made sure it was CHMOD +x, 777 and owned by plex:plex

I must have missed something simple...

Ubuntu 18.04

**Comment by nebhead** [comment]
Do you see the tmp.zzWHyMdI08.mkv file in the /tmp folder?

**Comment by tykisson** [comment]
No the file wasn't there. 
I did move back to my old script and it stopped working as well. just went into a waiting loop after runn ffmpeg.

To clean the slate I removed everything from the /tmp folder, purged ffmpeg, autoremove and then reinstalled ffpmeg and set the new script in plex.
Just started a new recording, so we will see what happens and i'll report back.

**Comment by tykisson** [comment]
and the results:

> 20220427-201003: Transcoding /mnt/TyServer/TV/.grab/65cdd31695702f48566a08374524489f1f4819b7-9b8eddc818b8f19067a142c98ecadcc4334c356c/Tom & Jerry (1965) - S2007E$
Using FFMPEG [216M -> ] - [0 min 0 sec]
20220427-201003: Finished transcode,ERROR # 1 : Failed to move converted file: /tmp/tmp.heiOLLeW7M.mkv
>
The file in /tmp:
> -rw-r--r--  1 plex plex      0 Apr 27 20:10 tmp.JZiV7NxEhG.ppplock
>
.grab folder is empty. Plex did make a TV folder structure but it was empty as well.
I'm recording another spot and will run the script manually to see if anything else comes up.

Thoughts?
BTW - Sent you some beer money $$ Thanks for the support!

**Comment by nebhead** [comment]
Thanks for the logs, and thanks for the beer money!  I really appreciate that. 

OK, so given that the file doesn't exist and the grab folder is empty, it seems there is something strange going on.  TBH, it's been a while since I looked at my own setup, so I may try to do a test run over here as well.  

Did you make any changes to the settings at the top of the script? 
Are you running in a docker container, or in another environment?

**Comment by nebhead** [comment]
Well, look at that... I'm getting a similar error.  Here's a dump from my docker log:

```
20220427-190003: Transcoding /mnt/dionysus/Videos/Television/.grab/94f9716617ab443ba043008ae99ac2d7c72c63b4-f3772945ba9c2c6d10f6c622459518c3785fa44a/PBS NewsHour (2009) - S48E215 - PBS NewsHour.ts to /tmp/tmp.LLbI2wlgHx.mkv

ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers

  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)

  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared

  libavutil      56. 31.100 / 56. 31.100

  libavcodec     58. 54.100 / 58. 54.100

  libavformat    58. 29.100 / 58. 29.100

  libavdevice    58.  8.100 / 58.  8.100

  libavfilter     7. 57.100 /  7. 57.100

  libavresample   4.  0.  0 /  4.  0.  0

  libswscale      5.  5.100 /  5.  5.100

  libswresample   3.  5.100 /  3.  5.100

  libpostproc    55.  5.100 / 55.  5.100

Input #0, mpegts, from '/mnt/dionysus/Videos/Television/.grab/94f9716617ab443ba043008ae99ac2d7c72c63b4-f3772945ba9c2c6d10f6c622459518c3785fa44a/PBS NewsHour (2009) - S48E215 - PBS NewsHour.ts':

  Duration: 00:46:32.71, start: 1.400000, bitrate: 9949 kb/s
  Program 1 

    Metadata:

      service_name    : Service01

      service_provider: FFmpeg

    Stream #0:0[0x100]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc

    Stream #0:1[0x101](eng): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 256 kb/s

Unknown encoder 'libfdk_aac'

ls: cannot access '/tmp/tmp.LLbI2wlgHx.mkv': No such file or directory

Using FFMPEG [3.3G -> ] - [0 min 0 sec]

mv: cannot stat '/tmp/tmp.LLbI2wlgHx.mkv': No such file or directory

20220427-190003: Finished transcode,ERROR # 1 : Failed to move converted file: /tmp/tmp.LLbI2wlgHx.mkv
```

I see that FFMPEG is not fiding the libfdk_aac encoder.  I'll see if I can fix that and try again.

**Comment by nebhead** [comment]
Yeah, that was the problem.  I didn't realize with the latest PR that this audio codec selection was added by default.  I'm going to move it back to ac3 and that should solve the issue.  Thanks for bringing to my attention!

**Comment by nebhead** [comment]
OK, change has been made in the latest commit: https://github.com/nebhead/PlexPostProc/commit/08994816b185cba331da65d06fa11c45ed5a3aa0  

Pull the latest and give that a go.  I think that should clear up your problem.

**Comment by tykisson** [comment]
> 20220428-143103: Transcoding /mnt/TyServer/TV/.grab/35673a7d750d7829fb70a38088c30ee02c92380f-9b8eddc818b8f19067a142c98e$Using FFMPEG [230M -> 89M] - [7 min 56 sec]
20220428-143859: Finished transcode, exiting.

> 
I'm going to call that good!
