### ISSUE TITLE
QUESTION: Any way to keep subtitles?

### ISSUE THREAD

**Issue by Hollywood42** [nebhead/PlexPostProc#29]
I'd love to be able to keep subtitles in my file after processing but I'm not sure how to keep them in. Any of the options I've found online for both handbrake and ffmpeg have both either caused it to not output a file or didn't output the file with subs. Any ideas?

**Comment by nebhead** [comment]
This is a really good question.  I also haven't found a good way to do this, but it seems like it should be possible.  I'm open to ideas!

**Comment by Hollywood42** [comment]
I was able to get them in by adding in my own Handbrake settings and adding --all-subtitles I'll add the full line below. However, they subtitles only flash on the screen at the right time and don't stay on the screen long enough. I'll update if I can figure out how to fix it. 

`/usr/bin/HandBrakeCLI -i "$FILENAME" -o $TEMPFILENAME -f av_mkv -e x265 -q 26.0 --all-audio -E av_aac -B 320 --mixdown 5point1 --deinterlace mode=3 --decomb mode=7 --all-subtitles`
