### ISSUE TITLE
Possible to NOT delete the original file for trouble shooting?

### ISSUE THREAD

**Issue by eqpaisley** [nebhead/PlexPostProc#5]
I'm having a weird issue where my DVR recordings are not complete. Each recording is missing chunks within the episode it records. The beginning and end are intact but there are plays where the video seems to skip several minutes of the show (almost as if ComSkip were running on the video and doing a terrible job - except I'm not using ComSkip).  Can I set this script to NOT erase the original so that I can check where in the process the breakdown is happening?

**Comment by nebhead** [comment]
Yes.  Replace the line:

rm -f "$FILENAME"

With something like:

mv -f "$FILENAME" "$FILENAME.original.ts"

That should rename the original file to add ".original.ts" to the end.  It might not get processed by Plex, so the file might end up staying in the .grab folder.  Or it may get moved.  Anyway, good luck!
